### PR TITLE
chore: revert decode txs e2e

### PR DESCRIPTION
**Pull request by Torres-ssf**
This PR reverts commit [c83efa04182d22778927262ad04b4c907fe38197](https://github.com/FuelLabs/fuels-ts/commit/c83efa04182d22778927262ad04b4c907fe38197).

I am reverting this to avoid these tests resulting in more problems than solutions in the future.

See the related [discussion](https://github.com/FuelLabs/fuels-ts/pull/2354#discussion_r1606805442).

### CODE REVIEW

**Review by nedsalk — APPROVED** [review]

**Review by danielbate — COMMENTED** [review]
I still think [this](https://github.com/FuelLabs/fuels-ts/pull/2354#discussion_r1609881066) is valid. The [work](https://github.com/FuelLabs/fuels-ts/pull/2341) was added as #2238 missed this because of the lack of an `e2e`. But I can appreciate we can move this to an issue/discussion and further there.

**Comment by arboleya** [comment]
@danielbate I don't have the full context, and your points make sense.

Could you please summarize them in a new issue?

It'll be great to address this pattern more broadly.

**Review by danielbate — APPROVED** [review]
Approving, but let's follow up in #2373 as we will still need to test for these transaction types.

**Comment by arboleya** [comment]
@Torres-ssf We can close this for now and tackle the matter via https://github.com/FuelLabs/fuels-ts/issues/2373.

**Comment by Torres-ssf** [comment]
> @Torres-ssf We can close this for now and tackle the matter via #2373.

Ok @arboleya, thanks

**Pull request closed without merging**
