### PR TITLE
chore: re-enable connectors, bump dependencies

### LINKED ISSUE #2171: Update template use of `connectors`
After the `connectors` package updates `fuels`, we'd have to back and adjust this [commit](https://github.com/FuelLabs/fuels-ts/pull/2021/commits/a1fcca7bb365f848f6ac80c789a28841c0c0a56b).

### PR DESCRIPTION
**Pull request by Dhaiwat10**
This PR re-enables all the default connectors in the `create-fuels` template, and bumps `@fuels/react` and `@fuels/connectors` to their latest versions.

Closes #2171

### CODE REVIEW

**Review by nedsalk — DISMISSED** [review]
If only all PRs were one-liners!

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
Wait, is it possible to uncomment this already?

Is the connectors package using `fuels` `0.83` already?

**Comment by arboleya** [comment]
The relationship between `fuels` and `@fuels/connectors` looks problematic.

Because one depends on the other, their cyclic dependency should always hunt us and delay releases.

**Review by danielbate — DISMISSED** [review]

**Comment by Dhaiwat10** [comment]
There is indeed a version mis-match here. Marking this as blocked until the wallet SDK bumps their TS SDK version

**Review by Torres-ssf — APPROVED** [review]

**Review by arboleya — APPROVED** [review]

**Review by maschad — APPROVED** [review]

**Pull request merged**
