### PR TITLE
Revert recent repo refactor

### PR DESCRIPTION
**Pull request by AlicanC**
These changes broke my workflow as I've mentioned on https://github.com/FuelLabs/fuels-ts/pull/238#issuecomment-1118749157.

It also seems to have broken our publishing CI flow: https://github.com/FuelLabs/fuels-ts/pull/242

We should revert these changes and introduce them again when we are sure we won't have these regressions.

### CODE REVIEW

**Comment by luizstacio** [comment]
I think we should wait and push #242 to be merged.

**Comment by AlicanC** [comment]
It already has been 3 days :D

**Comment by pedronauck** [comment]
We merged #242 @AlicanC, CI is fixed and now you can use `pnpm build:watch` to build packages.

**Comment by AlicanC** [comment]
I'm on that branch and I'm not 100% sure we are done with regressions. I'll LYK.

**Comment by AlicanC** [comment]
The current issue I'm having is:

```
On fuels-ts:
- Run `pnpm i`
- Run `pnpm -r exec yarn link`
- Run `pnpm build:watch`

On swayswap:
- Run `yarn link fuels typechain-target-fuels`
- Run `yarn start`

On fuels-ts:
- Make a change and save

On swayswap:
- CRA doesn't see the changes, I need to stop and run `yarn start` again
```

Anyways, I've spent hours on #238 this week and I need to get back to work. It's just not working for me and I'll be working on my reverted branch.

**Comment by luizstacio** [comment]
> The current issue I'm having is:
> 
> ```
> On fuels-ts:
> - Run `pnpm i`
> - Run `pnpm -r exec yarn link`
> - Run `pnpm build:watch`
> 
> On swayswap:
> - Run `yarn link fuels typechain-target-fuels`
> - Run `yarn start`
> 
> On fuels-ts:
> - Make a change and save
> 
> On swayswap:
> - CRA doesn't see the changes, I need to stop and run `yarn start` again
> ```
> 
> Anyways, I've spent hours on #238 this week and I need to get back to work. It's just not working for me and I'll be working on my reverted branch.

I think this is what you are looking for, I also had the same problem, and we [fix it here](https://github.com/FuelLabs/fuels-ts/pull/246);

To link the packages you need to;

On `fuesl-ts` root directory;
- Run `pnpm -r exec pnpm link --global --dir ./`
- If you want to have live reload on the project to automatically sync changes on the packages run also; 
  -`pnpm pnpm build:watch`

On the `swayswap` root folder;
- `pnpm link --global <linked package name>` 
Ex.: 
- Make sure `yarn start` is not running
- `pnpm link --global fuels`
- `pnpm link --global @fuel-ts/wallet`
- Run `yarn start`

Maybe we should add something like this to the docs.
Ref.: https://github.com/FuelLabs/fuels-ts#build-and-watch-all-packages

**Comment by luizstacio** [comment]
Just open a PR to improve the docs also; https://github.com/FuelLabs/fuels-ts/pull/254

**Comment by luizstacio** [comment]
@AlicanC we can close this?

**Comment by AlicanC** [comment]
- Run `pnpm build:watch`
- Go to `packages/providers/src/script.ts`
- Rename `class Script` to `class ScriptFoo`
- You will see a build error as expected
- Revert the change and fix the error
- Rename `getArgOffset` to `getArgOffsetFoo`
- You see no errors

It's probably because unlike `Script`, `getArgOffset` is not used in the `providers` package itself. If you go to `packages/contract/src/scripts.ts` you see the error in the editor though. (You don't get this error even if you run `pnpm build`.)

How can I see all TS errors over all packages while developing?

**Comment by AlicanC** [comment]
Also, have you tried linking `typechain-target-fuels`? (`pnpm link --global fuels typechain-target-fuels`)

I tried to run `yarn build-contracts` on SwaySwap client and it said `js-sha3 not found` or something like that. Turning on this feature fixed it: https://pnpm.io/npmrc#shamefully-hoist

Seems like PNPM is trying to do some tricks like Yarn 2 does with Plug'n'Play and breaking things.

**Comment by luizstacio** [comment]
@AlicanC should we merge master and move with this?

**Comment by AlicanC** [comment]
Even though we wanted to revert this PR isn't the way.

**Pull request closed without merging**
