### PR TITLE
chore: symlink `docs/CONTRIBUTING.md` on repo root

### PR DESCRIPTION
**Pull request by Franqsanz**
Hi, I have added the CONTRIBUTING.md file to the root of the project. Solving the issue: #693

### CODE REVIEW

**Comment by arboleya** [comment]
Could you please use a relative symlink instead of duplicating the `docs/CONTRIBUTING.md` file?

This will prevent these files from going outdated.

**Comment by Franqsanz** [comment]
Hello @arboleya, I have a question, should I add the link in the same way that it is in the PR that you pointed out to me? Inside the `packages/fuels/package.json` and then in the `files` field?

Thank you.

**Comment by arboleya** [comment]
No, I am referring to [symlinks](https://en.wikipedia.org/wiki/Symbolic_link).

For example:

```console
$ cd fuels-ts
$ ln -s ./docs/CONTRIBUTING.md ./CONTRIBUTING.md
```

> _Sidenote: Remember to add an empty changeset to your PR._

**Comment by Franqsanz** [comment]
Hello, Here is the link, if there is something wrong, feel free to tell me!

**Review by arboleya — APPROVED** [review]

**Pull request merged**
