### PR TITLE
chore: upgrading forc to `0.32.2` and fuel-core to `0.15.1`

### PR DESCRIPTION
**Pull request by arboleya**
- Close: #657

### CODE REVIEW

**Comment by arboleya** [comment]
I'm having a hard time trying to update `fuel-core` to `0.15.0` here. The tests inside the `fuel-gauge` package seem flaky. Each time I run `pnpm test`, at least one test fails. If I rerun it, another test fails _(and the previous will pass!)_.

On rare occasions, all tests will pass (_check the **`Test Ouput`** below_)

This makes it very hard to understand what's happening or what/where the problem is.

Ideas?

> _cc @camsjams @LuizAsFight @luizstacio_ 

<details>
  <summary>Test Ouput</summary>

passing

</details>

**Comment by arboleya** [comment]
@camsjams The latest commit from yesterday seemed to have hit the rare occasion where all tests passed, but I don't feel confident about moving with this merge just yet.

Thoughts I have:
 1. Where should I start investigating the tests' flakiness _(if any)_
 2. What are the main concerns when doing these updates?
 3. Should I look for breaking changes in some place specifically?

Could you please help me triage this one?

> cc @digorithm

**Comment by Dhaiwat10** [comment]
As of now all the CI checks are passing 🤔

**Comment by LuizAsFight** [comment]
@arboleya 

can check changelog of fuel-core, normally breaking changes can be found there
https://github.com/FuelLabs/fuel-core/releases

**Review by Dhaiwat10 — DISMISSED** [review]

**Review by Dhaiwat10 — APPROVED** [review]

**Pull request merged**
