### PR TITLE
test: using `getForcProject` instead of manually reading files

### PR DESCRIPTION
**Pull request by Torres-ssf**
Standardizing test suites by using `getForcProject` instead of manually reading files

### CODE REVIEW

**Review by arboleya — COMMENTED** [review]
Great initiative! ✨ 

I believe these approaches are cleaner, though.

It is also good/handy to have paths predictably set in a single place.

 - [docs-snippets/projects/index.ts](https://github.com/FuelLabs/fuels-ts/blob/st/test/using-get-forc-project/apps/docs-snippets/projects/index.ts)

 - [abi-typegen/test/fixtures/forc-projects/index.ts](https://github.com/FuelLabs/fuels-ts/blob/st/test/using-get-forc-project/packages/abi-typegen/test/fixtures/forc-projects/index.ts)

**Comment by nedsalk** [comment]
@Torres-ssf I'm planning on applying #1356 to all tests (to close #296), so we might be doing conflicting work. Could you please put this PR on hold until #1356 is reviewed by the team?

**Comment by arboleya** [comment]
This PR standardizes lots of things; let's move on with this and get it merged.

Two more weeks have passed, and things are _not_ looking pretty for #1356.

If and when it comes to fruition, we can resolve conflicts as usual.

We should not wait for it any longer.

**Comment by Torres-ssf** [comment]
> This PR standardizes lots of things; let's move on with this and get it merged.
> 
> Two more weeks have passed, and things are _not_ looking pretty for #1356.
> 
> If and when it comes to fruition, we can resolve conflicts as usual.
> 
> We should not wait for it any longer.

@arboleya I agree. Thanks

**Review by arboleya — APPROVED** [review]

**Review by danielbate — APPROVED** [review]

**Pull request merged**
