### PR TITLE
chore: add generated file cache to CI

### PR DESCRIPTION
**Pull request by danielbate**
Resolves [this](https://github.com/FuelLabs/fuels-ts/actions/runs/7700472458/job/20984720952) CI error.

`docs` is not hitting the cache as one of the cache inputs is generated on build. We should therefore also cache generated files to ensure cache validity is correctly checked.

Cache executed [here](https://github.com/FuelLabs/fuels-ts/actions/runs/7708611216/job/21008433835?pr=1694#step:3:34).

### CODE REVIEW

**Comment by petertonysmith94** [comment]
Suggest passing through the `cache-path` as input arguments.

**Comment by danielbate** [comment]
@petertonysmith94 please can you provide an example? And what's the benefit of this?

**Comment by petertonysmith94** [comment]
Hey @danielbate,
I suppose for me only having to update 2 places, rather than 4 is worth it.

This is a untested test commit, was only a suggestion :)
https://github.com/FuelLabs/fuels-ts/commit/b284d423f35fc50eba9877b561768536a045554a

**Review by Torres-ssf — APPROVED** [review]

**Review by arboleya — APPROVED** [review]
🎯

**Pull request merged**
