### PR TITLE
build: update deps

### PR DESCRIPTION
**Pull request by maschad**
I explained [here](https://github.com/FuelLabs/fuels-ts/pull/2157#pullrequestreview-2020356177) the rationale for re-opening this.

This undoes the revert done [here](https://github.com/FuelLabs/fuels-ts/pull/2157) I chose to use the original branch as a _revert of a revert_ would make the commit history look less readable.

I've ran these tests in the browser [at least 4 times](https://github.com/FuelLabs/fuels-ts/actions/runs/8822911152) with no failures so I think it's safe to merge.

### CODE REVIEW

**Review by Dhaiwat10 — APPROVED** [review]

**Review by nedsalk — DISMISSED** [review]

**Review by arboleya — DISMISSED** [review]

**Review by danielbate — CHANGES_REQUESTED** [review]
After doing some testing of this upgrade with this work integrated in both [mine](https://github.com/FuelLabs/fuels-ts/pull/1976) and @Torres-ssf [work](https://github.com/FuelLabs/fuels-ts/pull/2021). I think it would be best to delay the release of this work until after the [first wave](https://github.com/FuelLabs/fuels-ts/issues/2151) of releases. And to also do further testing, specifically to the `vitest` upgrade. One option couple be to decouple the `vite`/`vitest` upgrades from the other package upgrades?

Firstly, we've both experienced significant performance degradation locally when running the `ci:test` suite when we had this work integrated with our own. Upon [cherry-picking the revert](https://github.com/FuelLabs/fuels-ts/pull/1976/commits/cf5e2ce50f0051bedac2dd16961d1c8e7858fb8b), these problems no longer persisted. Sergio said it was at times, unusable. My problems got exponentially worse but not unusable.

Another problem, and potentially related to the flaky tests and performance issue was a new warning appearing related to our `vitest` setup: `Vitest found 6 config files. For better performance, consider using a workspace configuration.`. I think we should first add a [workspace configuration](https://vitest.dev/guide/workspace), and then proceed to see if that completely resolves the above issues.

However I do agree, these upgrades bring essential value that should still be prioritised after the first wave release.

**Comment by maschad** [comment]
> Another problem, and potentially related to the flaky tests and performance issue was a new warning appearing related to our vitest setup: Vitest found 6 config files. For better performance, consider using a workspace configuration.. I think we should first add a [workspace configuration](https://vitest.dev/guide/workspace), and then proceed to see if that completely resolves the above issues. 
 
 That's a good point, I created this issue to handle the [vitest upgrade](https://github.com/FuelLabs/fuels-ts/issues/2169) and changed this PR to only upgrade `vite`.

**Comment by maschad** [comment]
> ESM only package

The `vite.config.ts` files we have already in ESM syntax so I don't think this is an issue, that recommendation is for troubleshooting non-ESM compatible imports.

**Review by Torres-ssf — DISMISSED** [review]

**Comment by Torres-ssf** [comment]
I had no issues running the tests using this branch

**Comment by maschad** [comment]
> Just merged `master` and got the [error](https://github.com/FuelLabs/fuels-ts/actions/runs/8891154219/job/24412537599#step:10:348) we experienced before the release.
> 
> > FAIL  packages/utils/src/utils/chunkAndPadBytes.test.ts [ packages/utils/src/utils/chunkAndPadBytes.test.ts ]
> > Error: No test suite found in file /home/runner/work/fuels-ts/fuels-ts/packages/utils/src/utils/chunkAndPadBytes.test.ts
> 
> There are also a lot of [warnings](https://github.com/FuelLabs/fuels-ts/actions/runs/8891154219/job/24412537599#step:10:33) within the `browser` tests which aren't visible on [master](https://github.com/FuelLabs/fuels-ts/actions/runs/8891293490/job/24412968301#step:10:115).
> 
> > Module "util" has been externalized for browser compatibility. Cannot access "util.debuglog" in client code. See [vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility](https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility) for more details.

Good catch @petertonysmith94 , it seems my [previous lockfile](https://github.com/FuelLabs/fuels-ts/pull/2158/commits/38cf10d5c58f0b5127b7b743ffc480a0902e3972) was causing [vitest to run v1.5](https://github.com/FuelLabs/fuels-ts/actions/runs/8891154219/job/24412537599#step:10:23) despite those deps not being updated to that vitest version, a bit strange considering that's outside the semver range, must have been a pnpm install oversight... nevertheless I've resolved that and [the warnings and flakey test](https://github.com/FuelLabs/fuels-ts/actions/runs/8902104865/job/24447374313?pr=2158#step:10:23) are gone now 😄

**Review by Dhaiwat10 — APPROVED** [review]

**Review by arboleya — APPROVED** [review]
Good one! 💪 

I just tested this branch locally, and everything went well.

Please remember to double-check it after it goes to `master`. 🙂

**Pull request merged**
