### PR TITLE
Fix: Corrected types property in package.json files

### LINKED ISSUE #3208: Adjust `types` property in all `package.json` files
We need to replicate this to all packages: https://github.com/FuelLabs/fuels-ts/pull/3190/commits/3d0c0f6432297912caa3bb67bd632258d375aef3

It seems that the `types` property must be the first, otherwise we get a warning:

```
Warning: G] The condition "types" here will never be used as it comes after both "import" and "require" [package.json]

    ../../package.json:19:6:
      19 │       "types": "./dist/index.d.ts"
         ╵       ~~~~~~~
```

_Originally posted by @petertonysmith94 in https://github.com/FuelLabs/fuels-ts/pull/3190#discussion_r1773851228_

### PR DESCRIPTION
**Pull request by Namanedogawa**
Issues закрываемые этим PR:

Closes #3208
Release Notes:

In this release, we:

Corrected the types property in package.json files across multiple packages.
Summary:

This PR fixes an issue where the "types" property in package.json files was not positioned correctly. The types property should be listed first to avoid any potential issues during compilation. A script was used to automatically detect and correct these errors.

Breaking Changes:

None.

Checklist:

 [x]All changes are covered by tests (or not applicable)
 [x]All changes are documented (or not applicable)
 [x]I reviewed the entire PR myself (preferably, on GH UI)
 [x]I described all Breaking Changes (or there's none)

### CODE REVIEW

**Comment by Namanedogawa** [comment]
This PR ensures that the types property is correctly positioned as the first property in all package.json files to avoid potential warnings during compilation.

**Comment by danielbate** [comment]
Hey @Namanedogawa, thanks for the contribution!

We love to get submissions from the community, but we prefer first-time contributions to be more substantial. If you are excited to make a contribution, feel free to look through our [open issues](https://github.com/FuelLabs/fuels-ts/issues) for ideas!

Closing for now.

**Comment by Namanedogawa** [comment]
Hi @danielbate, thank you very much for such a quick response, but I closed one issue for you, how can this not be enough?

**Comment by danielbate** [comment]
Hi @Namanedogawa, genuinely thank you for making a contribution to the SDK and apologies for closing without much comment.

This is a high priority issue that we are in a rush to release so we've made the decision to tackle this internally.

Check out our other [issues](https://github.com/FuelLabs/fuels-ts/issues), the `good-first-issue` label is a good place to start or feel free to tag my self in any you've got your eye on and I may be able to provide some more context.

**Comment by Namanedogawa** [comment]
Thank you very much for your answer and help! You are the best!

**Pull request closed without merging**
