### PR TITLE
fix: add missing receipts properties

### LINKED ISSUE #3155: Add Receipts Missing Properties
Some receipt types are missing certain properties:

- `ReceiptReturnData.data`
- `ReceiptLogData.data`
- `ReceiptMessageOut.len`

Some of these missing properties are currently being [injected](https://github.com/FuelLabs/fuels-ts/blob/5efe23d5969d9815bc863f93991968cc6484d230/packages/account/src/providers/transaction-summary/receipt.ts#L13-L23) into parsed receipts, instead of being assigned during the [receipt parsing process](https://github.com/FuelLabs/fuels-ts/blob/5efe23d5969d9815bc863f93991968cc6484d230/packages/account/src/providers/utils/receipts.ts#L64).

### PR DESCRIPTION
**Pull request by Torres-ssf**
> Fixes TS-647
- Closes #3155

# Checklist

- [x] All **changes** are **covered** by **tests** (or not applicable)
- [x] All **changes** are **documented** (or not applicable)
- [x] I **reviewed** the **entire PR** myself (preferably, on GH UI)
- [x] I **described** all **Breaking Changes** (or there's none)

### CODE REVIEW

**Review by maschad — COMMENTED** [review]
Nice work @Torres-ssf Given that this method is used in `dryRun` , `estimateTxDependencies`, `estimateMultipleTxDependencies`  and `simulate` Provider methods, as well as the [transaction summary methods](https://github.com/FuelLabs/fuels-ts/blob/master/packages/account/src/providers/transaction-summary/get-transaction-summary.ts#L26) , should we add `fuel-gauge` tests to capture this change in the receipts?

**Comment by Torres-ssf** [comment]
> Nice work @Torres-ssf Given that this method is used in `dryRun` , `estimateTxDependencies`, `estimateMultipleTxDependencies` and `simulate` Provider methods, as well as the [transaction summary methods](https://github.com/FuelLabs/fuels-ts/blob/master/packages/account/src/providers/transaction-summary/get-transaction-summary.ts#L26) , should we add `fuel-gauge` tests to capture this change in the receipts?

@maschad I have updated the unit test where parsed receipts properties are validated https://github.com/FuelLabs/fuels-ts/pull/3156/commits/8cdfd237b374e36e42cfafeabd059f425124ae96

**Comment by maschad** [comment]
@Torres-ssf I observed that, but that relies on mock data, do you not feel that our _end-to-end_ / fuel-gauge tests would capture this type of inconsistency more readily given it's closer to a consumer API interaction?

**Comment by Dhaiwat10** [comment]
Why is this PR causing such a significant performance regression? 👁️

**Review by petertonysmith94 — APPROVED** [review]

**Comment by petertonysmith94** [comment]
> @Torres-ssf I observed that, but that relies on mock data, do you not feel that our _end-to-end_ / fuel-gauge tests would capture this type of inconsistency more readily given it's closer to a consumer API interaction?

IMO as these coders are due for deprecation, mocked data is sufficient for now.

**Comment by maschad** [comment]
Good point @petertonysmith94

**Review by maschad — APPROVED** [review]

**Pull request merged**
