### PR TITLE
feat: add `fuel-ts/utils` to `fuels` umbrella package

### PR DESCRIPTION
**Pull request by LuizAsFight**

### CODE REVIEW

**Review by arboleya — CHANGES_REQUESTED** [review]
Cool! What utility are you planning to use from this package?

Also, please add simple mentions and assertions for `@fuel-ts/utils` exported methods in the tests below. This should prevent unintentional deletion and ensure proper building.

 - [internal/check-imports/src/imports.ts](https://github.com/FuelLabs/fuels-ts/blob/lf/chore/add-utils-fuels/internal/check-imports/src/imports.ts)
 - [internal/check-imports/src/references.ts](https://github.com/FuelLabs/fuels-ts/blob/lf/chore/add-utils-fuels/internal/check-imports/src/references.ts)

**Comment by arboleya** [comment]
> Also, please add simple mentions and assertions [..]

I expressed myself badly.

What I meant is that it'd be nice to import something from the `@fuel-ts/utils` via the `fuels` import here:

https://github.com/FuelLabs/fuels-ts/blob/1ad5c3be5cdaf43d30f73ce2987720c48b1a247b/internal/check-imports/src/references.ts#L31

Something like:

```ts
import {
  ScriptRequest,
  capitalizeString
  chunkAndPadBytes
  normalizeString
  concatBytes,
} from 'fuels'; 
```

**Comment by LuizAsFight** [comment]
> > Also, please add simple mentions and assertions [..]

initial reason is that sdk use to have a `concat` function exported in `fuels` and now it was purged in this PR: #1316 
now the function is called `concatBytes` but we don't have access to it in `fuels` anymore.

I will install `@fuel-ts/utils` to unblock myself here and continue my work

but I'm creating this PR as I think this should also be added to `fuels` umbrella package, and also other methods in `utils` are very _util🤓_ and it's worth adding.

sorry for putting it straight to review @arboleya 
can someone in sdk team pick this one up to finish?

**Comment by arboleya** [comment]
I got ya!

**Review by arboleya — APPROVED** [review]

**Review by Torres-ssf — APPROVED** [review]

**Comment by arboleya** [comment]
@LuizAsFight Released in `0.64.1`.

**Pull request merged**
