### PR TITLE
chore: export test and cli utilities in `fuels` umbrella package

### LINKED ISSUE #2223: Export [test] utilities in umbrella package
We should export all secondary entry points (utilities) using dedicated entry points in the `fuels` umbrella package.

For example:
 - `fuels/test-utils` — all `test` utilities from all sub-packages
 - `fuels/cli-utils` — all `CLI` utilities from all sub-packages

The idea is that each of these would consolidate all utilities of the same group.

A few examples I grabbed from the codebase:

```ts
import { generateTestWallet } from '@fuel-ts/account/test-utils';
import { expectToThrowFuelError } from '@fuel-ts/errors/test-utils';
import { findBinPath } from '@fuel-ts/utils/cli-utils';
```

The umbrella package should be the only thing users should have to deal with.

### PR DESCRIPTION
**Pull request by nedsalk**
I exported the utils via the `fuels` umbrella package and changed imports to import from `fuels` accordingly. The changes in this PR are exclusively tied to that and running `pnpm lint:fix` afterwards.

- closes #2223

### CODE REVIEW

**Review by danielbate — DISMISSED** [review]

**Review by arboleya — APPROVED** [review]

**Review by Torres-ssf — APPROVED** [review]

**Review by maschad — COMMENTED** [review]
This looks fine, but I naive search in my code editor shows up 134 files, could we be missing some changes here?

Screenshot 2024-07-01 at 11 11 14 AM

**Comment by nedsalk** [comment]
@maschad you searched for `/test-utils` which is showing results for `fuels/test-utils`, `@fuel-ts/utils/test-utls`, `@fuel-ts/account/test-utils`, etc. This consolidates it all to use import from `fuels/test-utils`.

**Review by maschad — CHANGES_REQUESTED** [review]
I checked out onto this branch there are still a number of files that import from:

- `@fuel-ts/errors/test-utils`
- `@fuel-ts/account/test-utils`
- `@fuel-ts/utils/test-utils`

There's also some outdated docs / snippets such as:
- https://github.com/FuelLabs/fuels-ts/blob/ns/chore/export-utilities-in-umbrella-package/packages/account/README.md#L50
- https://github.com/FuelLabs/fuels-ts/blob/ns/chore/export-utilities-in-umbrella-package/apps/docs-snippets/src/guide/wallets/test-wallets.test.ts#L12

**Comment by maschad** [comment]
> @maschad you searched for `/test-utils` which is showing results for `fuels/test-utils`, `@fuel-ts/utils/test-utls`, `@fuel-ts/account/test-utils`, etc. This consolidates it all to use import from `fuels/test-utils`.

Thanks for the clarification, if you update the search to be explicit for `@fuel-ts/errors/test-utils`
`@fuel-ts/account/test-utils` and `@fuel-ts/utils/test-utils` you will see quite a few files. I've elaborated more [here](https://github.com/FuelLabs/fuels-ts/pull/2637#pullrequestreview-2152173114)

**Review by danielbate — COMMENTED** [review]
@maschad we should still be importing from the mono packages themselves rather than the umbrella inside the packages though shouldn't we? Filter your search to check only where we are installing `fuels` i.e. `packages/fuel-gauge` and `docs-snippets`. But you're correct around outdated docs.

**Comment by nedsalk** [comment]
@danielbate is right in https://github.com/FuelLabs/fuels-ts/pull/2637#pullrequestreview-2153497159.

As for the snippets and some leftovers that I didn't fix, I fixed them in https://github.com/FuelLabs/fuels-ts/pull/2637/commits/f980df50428e24509449dd11ee6dfd8109aa82f7 and https://github.com/FuelLabs/fuels-ts/pull/2637/commits/5131778d863af12360e13ebb5fbd0aba5cd9d957.

**Review by danielbate — APPROVED** [review]

**Review by maschad — APPROVED** [review]
Thanks for the clarification @danielbate 

Good job @nedsalk

**Review by Torres-ssf — APPROVED** [review]

**Pull request merged**
