### PR TITLE
fix: handle encoding and fn_selector resolving of `raw untyped ptr`

### PR DESCRIPTION
**Pull request by segfault-magnet**
closes: #547 

Not sure if there is anything else that needs bumping when doing a forc update.

### CODE REVIEW

**Comment by segfault-magnet** [comment]
Also not sure what to do about the CI lint phase failing:
```text
🦋  error Some packages have been changed but no changesets were found. Run `changeset add` to resolve this error.
🦋  error If this change doesn't need a release, run `changeset add --empty`.
```

**Review by arboleya — CHANGES_REQUESTED** [review]

**Comment by arboleya** [comment]
> Not sure if there is anything else that needs bumping when doing a forc update.

Is this a breaking change? If so, I believe a `minor` bump. Otherwise, a `patch` one. 

@luizstacio Please confirm. 👆 

> Also not sure what to do about the CI lint phase failing:

Please, implement the changes I request [here](https://github.com/FuelLabs/fuels-ts/pull/565#discussion_r1009428131). 

Then re-generate the changeset — `pnpm changeset:next`.

**Comment by segfault-magnet** [comment]
> Is this a breaking change?

After this is merged, fuels-ts vector support will cease for forc < v0.28.0 and function only for v0.28.0+.

Dunno if that broke enough things for a minor bump :)

**Comment by segfault-magnet** [comment]
> Then re-generate the changeset — pnpm changeset:next.

I haven't used `changeset`. Can you clear up a few points for me? @arboleya 
I ran `pnpm changeset:next` and it created a file `fuels-ts/.changeset/fuel-labs-ci.md` with the following content:
```text
---
"fuels": patch
---

incremental
```

I'm guessing the command didn't have any other side effects besides this. Am I to commit this file and when a release is done the CI will know to bump the version of `fuels`? Will this bump the `forc-bin` version I previously had changed manually? Or should I have run the command in the `forc-bin` package itself?

Also, in the file, it says `patch`. [Still waiting](https://github.com/FuelLabs/fuels-ts/pull/565#issuecomment-1297120788) for a verdict on that one, but if it ends up being 'do a minor bump', am I to change `patch` -> `minor` and all is well?

Hopefully, the CI gets its forc binary from the `forcVersion` and not the package version of `fuel-bin` otherwise it is going to fail due to the `forc` version being `0.26.something`

**Comment by luizstacio** [comment]
> > Then re-generate the changeset — pnpm changeset:next.
> 
> I haven't used `changeset`. Can you clear up a few points for me? @arboleya I ran `pnpm changeset:next` and it created a file `fuels-ts/.changeset/fuel-labs-ci.md` with the following content:
> 
> ```
> ---
> "fuels": patch
> ---
> 
> incremental
> ```
> 
> I'm guessing the command didn't have any other side effects besides this. Am I to commit this file and when a release is done the CI will know to bump the version of `fuels`? Will this bump the `forc-bin` version I previously had changed manually? Or should I have run the command in the `forc-bin` package itself?
> 
> Also, in the file, it says `patch`. [Still waiting](https://github.com/FuelLabs/fuels-ts/pull/565#issuecomment-1297120788) for a verdict on that one, but if it ends up being 'do a minor bump', am I to change `patch` -> `minor` and all is well?
> 
> Hopefully, the CI gets its forc binary from the `forcVersion` and not the package version of `fuel-bin` otherwise it is going to fail due to the `forc` version being `0.26.something`

To add a changeset you should run the command `pnpm changeset add` this will show some instructions and ask you to add the summary, the summary should be an understandable text for the change, in order to improve the changelog.

**Comment by segfault-magnet** [comment]
> > > Then re-generate the changeset — pnpm changeset:next.
> > 
> > 
> > I haven't used `changeset`. Can you clear up a few points for me? @arboleya I ran `pnpm changeset:next` and it created a file `fuels-ts/.changeset/fuel-labs-ci.md` with the following content:
> > ```
> > ---
> > "fuels": patch
> > ---
> > 
> > incremental
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm guessing the command didn't have any other side effects besides this. Am I to commit this file and when a release is done the CI will know to bump the version of `fuels`? Will this bump the `forc-bin` version I previously had changed manually? Or should I have run the command in the `forc-bin` package itself?
> > Also, in the file, it says `patch`. [Still waiting](https://github.com/FuelLabs/fuels-ts/pull/565#issuecomment-1297120788) for a verdict on that one, but if it ends up being 'do a minor bump', am I to change `patch` -> `minor` and all is well?
> > Hopefully, the CI gets its forc binary from the `forcVersion` and not the package version of `fuel-bin` otherwise it is going to fail due to the `forc` version being `0.26.something`
> 
> To add a changeset you should run the command `pnpm changeset add` this will show some instructions and ask you to add the summary, the summary should be an understandable text for the change, in order to improve the changelog.

Great, ty. The UX is friendly enough. 

The only thing left is to figure out the severity of the version bumps for packages `abi-coder` and `forc-bin`.

Any thoughts?

**Comment by arboleya** [comment]
@segfault-magnet I've forgotten we had [this](https://github.com/FuelLabs/fuels-ts/blob/master/docs/CONTRIBUTING.md#steps-to-pr), apologies. As Luiz pointed out, the `pnpm changeset add` seems to be the correct command. And yes, the CI should read the `forcVesion` config.

 Let's see what @luizstacio says about the `minor` x `patch` dilemma.

**Comment by luizstacio** [comment]
> @segfault-magnet I've forgotten we had [this](https://github.com/FuelLabs/fuels-ts/blob/master/docs/CONTRIBUTING.md#steps-to-pr), apologies. As Luiz pointed out, the `pnpm changeset add` seems to be the correct command. And yes, the CI should read the `forcVesion` config.
> 
> Let's see what @luizstacio says about the `minor` x `patch` dilemma.

Both work, no problem to use a patch, the only restricted thing, for now, is to use major.
On wich to choose @arboleya was the correct minor for breaks and patches for small changes.

**Comment by segfault-magnet** [comment]
Added the changeset. Did `patch` bumps on both packages.

**Review by luizstacio — APPROVED** [review]

**Review by digorithm — APPROVED** [review]
:shipit: 

Thanks @segfault-magnet for taking the time to work through this ❤️

**Pull request merged**
