### PR TITLE
Yatut1901/feature/migrate-to-app-routing

### PR DESCRIPTION
**Pull request by YaTut1901**
closes https://github.com/FuelLabs/fuels-ts/issues/2517

### CODE REVIEW

**Review by arboleya — COMMENTED** [review]
Conflicts to fix.

**Comment by YaTut1901** [comment]
@petertonysmith94 app routing structure requires all pages files to be in separate folders. Routing takes uri from the name of folder: https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#pages. This anyway requires folder structure to be changed, I just made all changes consistent

**Comment by YaTut1901** [comment]
okay, got it

**Comment by YaTut1901** [comment]
Will you merge your branch, or do I need to rewrite my PR?

**Pull request closed without merging**
