### PR TITLE
fix: broken tests not stopping CI + coverage report action

### LINKED ISSUE #341: Make CI fail when tests not pass
With the latest changes on CI when tests do not fail as the process keeps running and obfuscates the issues.

Ex.: https://github.com/FuelLabs/fuels-ts/runs/6867495021?check_suite_focus=true

### PR DESCRIPTION
**Pull request by LuizAsFight**
- Tests now stop the CI process if them break
- Added action to report coverage in a `comment` inside the PR
- Remove `ci.yaml`. Now use only `pr.yaml` 

thanks @QuinnLee for helping and suggesting the github report action

Closes #341

### CODE REVIEW

**Comment by QuinnLee** [comment]
https://github.com/FuelLabs/fuels-ts/pull/342 I think we came to the same conclusion. 

But I think we can remove the coverage flag because it doesn't render it and use https://github.com/marketplace/actions/jest-coverage-comment-action instead

**Comment by adlerjohn** [comment]
I've removed the requirement on the old CI workflow.

**Comment by AlicanC** [comment]
How do we know what failed? I can't see the details:
image

**Review by AlicanC — APPROVED** [review]

**Comment by adlerjohn** [comment]
Having CI failing properly is at least better than the status quo, and CI can be ran locally to figure out what failed. Improving the logs in CI can be left for a future PR.

**Comment by QuinnLee** [comment]
I think we should not use the `pnpm ci:test-coverage` and replace it with `pnpm ci:test` because in https://github.com/FuelLabs/fuels-ts/pull/342 it shows the failing tests and the coverage is no longer needed via jest

**Comment by AlicanC** [comment]
https://github.com/FuelLabs/fuels-ts/pull/342 fixes the issue and doesn't introduce anything else. I think we can merge that to fix the issue, and do the cool stuff like coverage reporting and merging the CI YAMLs here.

**Comment by LuizAsFight** [comment]
test logs is not showing in CI because of the github report action, which comments the coverage in the PR

if we prefer to show logs in CI over having the coverage comment here, we can use directly `pnpm cit:test:coverage`

**Comment by LuizAsFight** [comment]
@AlicanC It's fixed, now we can see the logs of failing tests in CI as well. Also has coverage comment enabled

**Pull request merged**
