### PR TITLE
feat: Replace workflows deprecated methods

### LINKED ISSUE #928: Replace workflows deprecated methods
A quick note about the `::set-output` command:

> **Warning**: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Perhaps it'd be good to review all current workflows and standardize the way we pass data between different steps.

_Originally posted by @arboleya in https://github.com/FuelLabs/fuels-ts/pull/903#discussion_r1176611792_

### PR DESCRIPTION
**Pull request by tibi77**
Should fix #928

### CODE REVIEW

**Comment by tibi77** [comment]
@arboleya -> should be good now

**Review by Dhaiwat10 — APPROVED** [review]
Thanks @tibi77, LGTM!

**Comment by tibi77** [comment]
@arboleya  could you have another look?

**Review by arboleya — APPROVED** [review]

**Review by Torres-ssf — APPROVED** [review]

**Comment by tibi77** [comment]
I don t have access to merge this, could someone do this :)

**Pull request merged**
