### PR TITLE
feat: make `create-fuels` template app responsive

### LINKED ISSUE #2997: Ensure `create-fuels` template app is mobile-friendly
The app should be fully responsive and natively usable on mobile devices as well as larger screens. Currently, it's designed only with laptops/desktop screens in mind.

### PR DESCRIPTION
**Pull request by Dhaiwat10**
- Closes #2997 

# Release notes

In this release, we:

- Made the `create-fuels` template app mobile-friendly

# Summary

This PR adds a responsive navbar to the `create-fuels` template to ensure that it is usable on mobile devices as well.

# Checklist

- [x] All **changes** are **covered** by **tests** (or not applicable)
- [x] All **changes** are **documented** (or not applicable)
- [x] I **reviewed** the **entire PR** myself (preferably, on GH UI)
- [x] I **described** all **Breaking Changes** (or there's none)

### CODE REVIEW

**Review by danielbate — COMMENTED** [review]
Will this impact the UI integration tests at all?

**Comment by Dhaiwat10** [comment]
@danielbate I don't think so 🤔 Is there a way to run them here?

**Comment by petertonysmith94** [comment]
@Dhaiwat10 I have been releasing to NPM then running the tests against the PR - as seen [here](https://github.com/FuelLabs/fuels-ts/pull/3035/commits/39614fd3a594165111502007327fb2fed9e7c121).

**Review by danielbate — DISMISSED** [review]

**Review by Torres-ssf — DISMISSED** [review]

**Review by danielbate — DISMISSED** [review]

**Review by maschad — DISMISSED** [review]

**Review by petertonysmith94 — DISMISSED** [review]

**Review by arboleya — DISMISSED** [review]

**Review by petertonysmith94 — APPROVED** [review]

**Review by danielbate — APPROVED** [review]
This feature is demoable in the [preview](https://create-fuels-template-git-dp-create-fuels-mobi-8da7a2-fuel-labs.vercel.app/) 🎉  Need to get it working against a testnet contract but WIP. Great work Dhai.

**Review by arboleya — APPROVED** [review]

**Pull request merged**
