### PR TITLE
fix: add missing gas limit support to Multicall

### PR DESCRIPTION
**Pull request by AlicanC**
It was possible to specify a custom gas limit for contract calls, but this information wasn't being passed to Multicall nor it was able to handle it. This PR cleans up Multicall, adds support for handling custom gas limits and makes the SDK forward this info to Multicall.

### CODE REVIEW

**Review by QuinnLee — DISMISSED** [review]

**Review by luizstacio — DISMISSED** [review]
LGTM

**Comment by AlicanC** [comment]
@luizstacio I've added tests, but they are blowing up since we wired the `gasLimit` wrong in #370.

I've left some comments there: https://github.com/FuelLabs/fuels-ts/pull/370#pullrequestreview-1032061141

**Comment by luizstacio** [comment]
> @luizstacio I've added tests, but they are blowing up since we wired the `gasLimit` wrong in #370.
> 
> I've left some comments there: [#370 (review)](https://github.com/FuelLabs/fuels-ts/pull/370#pullrequestreview-1032061141)

I answer your comments there, thanks for the review. I think we need to improve the `gasLimit` on a specific calls. I open an issue for that: https://github.com/FuelLabs/fuels-ts/issues/379

**Comment by luizstacio** [comment]
> > @luizstacio I've added tests, but they are blowing up since we wired the `gasLimit` wrong in #370.
> > I've left some comments there: [#370 (review)](https://github.com/FuelLabs/fuels-ts/pull/370#pullrequestreview-1032061141)
> 
> I answer your comments there, thanks for the review. I think we need to improve the `gasLimit` on a specific calls. I open an issue for that: #379

@AlicanC PR #380 is closed it should solve the issue on passing gas for each call.

**Review by luizstacio — APPROVED** [review]

**Pull request merged**
