### PR TITLE
fix: flaky predicate test

### PR DESCRIPTION
**Pull request by nedsalk**
This one has been failing in recent CI runs so I fixed it before #2457 to reduce flakiness.

### CODE REVIEW

**Comment by Torres-ssf** [comment]
Hey @nedsalk,

Do you know if this PR is still valid or should we close it?

**Comment by nedsalk** [comment]
@Torres-ssf it's valid and ready for review again, I fixed the problem. The amount required for the transfer from the predicate to happen was too small so I had to increase the `amountToPredicate` value quite a bit. Previously, this predicate was funded from multiple tests and thus was passing in some places and sometimes failing in other.

**Review by arboleya — APPROVED** [review]

**Comment by nedsalk** [comment]
Okay, so apparently me removing the seeding of this predicate address in this file's tests resulted in other tests failing because now _they_ don't have enough funds :cold_sweat: :hot_face: :cold_face:

I'm putting it into draft again.

**Comment by nedsalk** [comment]
#2457 is around the corner and I'll close this in favor of that PR.

**Pull request closed without merging**
