### PR TITLE
test: refactor predicate feature tests

### PR DESCRIPTION
**Pull request by danielbate**
Bringing some of the testing standards from #1043 to the predicate package, this PR does the following:

- Moves all predicate based tests from the `fuel-gauge` package into the predicate package inside a feature `tests` directory
- Refactored predicate based integration tests in `fuel-gage`
- Moved the predicate _unit_ tests also to the feature test directory in the `predicate` package
- Moved the integration and feature tests into more logical file structure and grouped based on functionality
- Refactored fixtures and types into appropriate directories
- Refactored tests to DRY up the code and moved shared code to `utils` directories
- Changed the language used in all test cases to follow the gherkin syntax and standardise

### CODE REVIEW

**Review by arboleya — COMMENTED** [review]
It seems that a lot of stuff is showing up ad deleted/added when it should appear as "renamed". This makes it harder to review big PRs since one needs to consider everything as new additions and, therefore, read it all over again.

Check this comment from @camsjams for a similar case:
 - https://github.com/FuelLabs/fuels-ts/pull/811#pullrequestreview-1340397880

In short, you'd need to delete/add things on the _same_ commit, so GIT understands it as a rename.

Could you please consider doing the same for this PR?

**Comment by danielbate** [comment]
@arboleya I definitely can merge the commits. I am concious however this won't get the desired effect due to the changes within the files, and that I have split 2 files into 8.

**Comment by danielbate** [comment]
Thankyou for the `fuel-gauge` insight @camsjams . As discussed over call with the @FuelLabs/sdk-ts team, `fuel-gauge` will remain the source for the integration tests. Therefore I will move the sway tests back into there, but maintaining the seperation of tests that this PR brings. With the view of bringing that to more areas of `fuel-gauge`.

**Comment by danielbate** [comment]
Thankyou for the `fuel-gauge` insight @camsjams . As discussed over call with the @FuelLabs/sdk-ts team, `fuel-gauge` will remain the source for the integration tests. Therefore I will move the sway tests back into there, but maintaining the seperation of tests that this PR brings. With the view of bringing that to more areas of `fuel-gauge`.

**Comment by danielbate** [comment]
@FuelLabs/sdk-ts I've now made changes based off our previous conversation around keeping integration tests in `fuel-gauge`. I'll update the testing standards in #1043 once this has been merged.

**Review by arboleya — APPROVED** [review]

**Pull request merged**
