### PR TITLE
chore: increate test timeout for e2e script

### PR DESCRIPTION
**Pull request by Torres-ssf**
I've seen this [report](https://github.com/FuelLabs/fuels-ts/actions/runs/9681310401/job/26713034958?pr=2624) 2 times already

### CODE REVIEW

**Review by nedsalk — APPROVED** [review]

**Review by maschad — DISMISSED** [review]
Looks like it's still [happening](https://github.com/FuelLabs/fuels-ts/actions/runs/9682379540/job/26716349177?pr=2632#step:5:37)

**Review by danielbate — APPROVED** [review]

**Comment by maschad** [comment]
@Torres-ssf the [error being thrown](https://github.com/FuelLabs/fuels-ts/actions/runs/9695374439/job/26755289443?pr=2632#step:5:20) seems related to devnet faucet, what leads you to believe a timeout increase would solve this?

**Comment by Torres-ssf** [comment]
> @Torres-ssf the [error being thrown](https://github.com/FuelLabs/fuels-ts/actions/runs/9695374439/job/26755289443?pr=2632#step:5:20) seems related to devnet faucet, what leads you to believe a timeout increase would solve this?

@maschad There seems to be an issue with the `devnet`, the problem is not specific to the faucet.

I misinterpreted the issue initially, thinking it was caused by a timeout. However, the timeout occurred due to the devnet issue. 

I will mark this PR as `awaiting` before closing it because I recall seeing this test fail a couple of times before due to timeout, but when the devnet was working properly, of course.

**Comment by maschad** [comment]
Sounds good @Torres-ssf , you may want to convert it to draft as well, or the `stale` automation may be disrupted if someone interacts with the PR mistakenly thinking it's ready for review. We can re-open for review when devnet is stabilized.

**Review by arboleya — APPROVED** [review]

**Pull request merged**
