### PR TITLE
chore: improve node incompatibility warning

### PR DESCRIPTION
**Pull request by Torres-ssf**
- Closes https://github.com/FuelLabs/fuels-ts/issues/2283

# Checklist

- [x] All **changes** are **covered** by **tests** (or not applicable)
- [x] All **changes** are **documented** (or not applicable)
- [x] I **reviewed** the **entire PR** myself (preferably, on GH UI)
- [x] I **described** all **Breaking Changes** (or there's none)

### CODE REVIEW

**Review by petertonysmith94 — APPROVED** [review]

**Review by maschad — APPROVED** [review]

**Review by nedsalk — APPROVED** [review]
It definitely is an improvement. Given that this part of the API shouldn't be changing anymore, I created https://github.com/FuelLabs/fuel-core/issues/2083 for network benefits. It'd make the changes in this PR obsolete, but I think it's worthwhile.

**Comment by petertonysmith94** [comment]
> It definitely is an improvement. Given that this part of the API shouldn't be changing anymore, I created [FuelLabs/fuel-core#2083](https://github.com/FuelLabs/fuel-core/issues/2083) for network benefits. It'd make the changes in this PR obsolete, but I think it's worthwhile.

@nedsalk Would this not lead to the same error messages that are in the [forum post](https://forum.fuel.network/t/fuels-typescript-sdk-error/5266)?

**Comment by nedsalk** [comment]
@petertonysmith94 No, because that error happened due to `fuel-core` version mismatches between beta-5 and testnet versions which had breaking changes between them. There shouldn't be such drastic breaking changes to the graphql API anymore so we can do it.

**Review by danielbate — APPROVED** [review]

**Comment by Torres-ssf** [comment]
@nedsalk I am not confident that breaking changes within the graphQL API will no longer happen.

**Review by arboleya — APPROVED** [review]

**Pull request merged**
