### PR TITLE
feat: adding `@fuel-ts/fuel-core` package

### PR DESCRIPTION
**Pull request by arboleya**
This PR adds a new package to the party — `@fuel-ts/fuel-core` is a bin wrapper around the original `fuel-core`.

This will be used to replace Docker and improve our tooling onward.

> **Note** It follows the `packages/forc` implementation.

### CODE REVIEW

**Review by danielbate — APPROVED** [review]
LGTM 👍🏻 Potentially out of scope of this PR, but following on from discussions yesterday and doesn't seem like it would be too difficult an extension to this feature, would to be able to specify the version to update to.

If a new version brought in breaking changes the only way to rollback would be manually. We could then also run the command in a test suite and pass versions for backwards compatibility checks?

**Comment by arboleya** [comment]
@danielbate Yes. For now, it's only a bin wrapper — I tried to keep this clean initially, but we can think about exposing a couple of API methods for more complex stuff.

**Review by Torres-ssf — APPROVED** [review]

**Review by Dhaiwat10 — APPROVED** [review]
🪄

**Comment by arboleya** [comment]
@danielbate @Dhaiwat10 @Torres-ssf I had to fix a conflict with `master`, and all reviews were dismissed.

This is the only new [commit](https://github.com/FuelLabs/fuels-ts/pull/1074/commits/cc22f2e5b907ce6a2ea27c7dc8dfb022245f701a).

**Review by danielbate — APPROVED** [review]

**Review by Dhaiwat10 — APPROVED** [review]

**Pull request merged**
