### PR TITLE
CI - Add S3 Assets Upload workflow

### PR DESCRIPTION
**Pull request by rfuelsh**

### CODE REVIEW

**Review by arboleya — DISMISSED** [review]
@rfuelsh I'm not sure I got this right, but I'm afraid we don't have any frontend assets on the TS SDK.

**Comment by rfuelsh** [comment]
please speak with @luizstacio - this was a request from him to devops team to create a S3 upload github actions pipeline- he is aware as this is his request

**Comment by rfuelsh** [comment]
going to close this - @luizstacio reach out to me when your team is ready for this

**Comment by luizstacio** [comment]
@arboleya @camsjams this is to enable the distribution of the fuels package via CDN.

**Pull request closed without merging**
