### PR TITLE
chore: reduce length of Vitest logged errors

### PR DESCRIPTION
**Pull request by Torres-ssf**
- Close: https://github.com/FuelLabs/fuels-ts/issues/2246

### CODE REVIEW

**Review by arboleya — DISMISSED** [review]

**Review by maschad — CHANGES_REQUESTED** [review]
I think we should probably address these [warnings](https://github.com/FuelLabs/fuels-ts/actions/runs/8972543737/job/24640748332?pr=2247#step:10:28) before merging, this was [raised previously](https://github.com/FuelLabs/fuels-ts/pull/2158#issuecomment-2084685787) by @petertonysmith94  when the vitest suite was being updated.

**Comment by arboleya** [comment]
@maschad Good catch! 🎯

**Comment by Torres-ssf** [comment]
> I think we should probably address these [warnings](https://github.com/FuelLabs/fuels-ts/actions/runs/8972543737/job/24640748332?pr=2247#step:10:28) before merging, this was [raised previously](https://github.com/FuelLabs/fuels-ts/pull/2158#issuecomment-2084685787) by @petertonysmith94 when the vitest suite was being updated.

@maschad https://github.com/FuelLabs/fuels-ts/pull/2247/commits/8fb83760ec167693aac2ca27fb1525337970cf47

**Review by maschad — APPROVED** [review]
Great job! That was fast 🚀

**Review by arboleya — APPROVED** [review]

**Pull request merged**
