### PR TITLE
WalletManager Package

### PR DESCRIPTION
**Pull request by luizstacio**
# Summary
- Add a package that manages many `Vaults` and `Accounts`.
- Add MemoryStorage to save the default state from `WalletManager`
- Add WalletManager component

# Description
WalletManager It's an upper component for Wallet that handles secrets or other `Wallet Types` connections.

### What is a Vault?
Vaults works like an adapter creating a single interface to connect to many secret providers, like Mnemonic, PrivateKey, and on the future `Hardware Wallets`.

### Storage
Create a single interface to work with any storage environment like `localStorage`, `browser.storage`, `indexedDB`, etc...

### TODO?
- [ ] Move `storages`, `vaults` and `Keystore` to separate packages
- [ ] Enable Export `vault secret` like `mnemonic phrase`

### Questions
- The name Vault makes sense?

clses: #118 , #119, #207

### CODE REVIEW

**Comment by AlicanC** [comment]
cc @adlerjohn for `Account`/`Vault` naming.

**Comment by luizstacio** [comment]
@adlerjohn can we merge this? If we think of other names we can refactor later.

**Comment by adlerjohn** [comment]
Oh wow I don't know how I missed this, sorry. I have no objections immediately. Can you file an issue to bikeshed over the name?

**Comment by luizstacio** [comment]
Open for future changes! Discussion here: https://github.com/FuelLabs/fuels-ts/issues/219

**Pull request merged**
