### PR TITLE
chore!: hotfix PR for connectors, will be removed

### PR DESCRIPTION
**Pull request by nedsalk**

### CODE REVIEW

**Comment by fuel-service-user** [comment]
✨ A PR has been created under the `rc-2224` tag on `fuels-wallet` repo.
https://github.com/FuelLabs/fuels-wallet/pull/1269

**Review by arboleya — COMMENTED** [review]
Converted to draft, as it's not meant to be merged.

**Comment by nedsalk** [comment]
Closing because it served its purpose.

**Comment by nedsalk** [comment]
@arboleya I had to create it as non-draft because the automatic workflow only publishes "ready for review" PRs.

**Comment by arboleya** [comment]
@nedsalk Thank you.

Are you sure non-draft PRs are not published?

I may be missing something, but I failed to find the such a conditional/distinction [in the code](https://github.com/FuelLabs/fuels-ts/blob/master/.github/workflows/pr-release.yaml).

**Comment by nedsalk** [comment]
@arboleya I was relying on [this](https://github.com/FuelLabs/fuels-ts/blob/master/.github/workflows/breaking-change-pr-release.yaml) automatic workflow initially which has that conditional.

**Comment by arboleya** [comment]
Got it. 👍

**Pull request closed without merging**
