### PR TITLE
chore: remove skip from the `waitForResult` test

### PR DESCRIPTION
**Pull request by mvares**
- Closes: #2773
# Checklist

- [x] I **_added_** — `tests` to prove my changes
- [ ] I **_updated_** — all the necessary `docs`
- [ ] I **_reviewed_** — the entire PR myself, using the GitHub UI
- [ ] I **_described_** — all breaking changes and the Migration Guide

### CODE REVIEW

**Comment by mvares** [comment]
The `timeout` defined here doesn't seem sufficient to cover the test duration. Do we need to increase the time?

https://github.com/FuelLabs/fuels-ts/blob/9a39997973267174f6c32ae5744c158d10f2b468/packages/fuel-gauge/src/transaction-response.test.ts#L203-L204

**Comment by petertonysmith94** [comment]
> The `timeout` defined here doesn't seem sufficient to cover the test duration. Do we need to increase the time?
> 
> https://github.com/FuelLabs/fuels-ts/blob/9a39997973267174f6c32ae5744c158d10f2b468/packages/fuel-gauge/src/transaction-response.test.ts#L203-L204

Did you experience any issues with this test timing out locally?

**Comment by mvares** [comment]
> Did you experience any issues with this test timing out locally?

Nops.

**Comment by petertonysmith94** [comment]
> > Did you experience any issues with this test timing out locally?
> 
> Nops.

I believe we can leave it for now - if it becomes an issue down the line then we can increment the timeout.

**Review by petertonysmith94 — APPROVED** [review]

**Review by arboleya — COMMENTED** [review]
CI is failing for all node versions.

**Comment by mvares** [comment]
> CI is failing for all node versions.

Yes. As mentioned above, the CI environment doesn't work exactly like the local environment. I believe we still need to increase it.

**Comment by arboleya** [comment]
On the topic of fixing flakiness with timeouts:
 - https://github.com/FuelLabs/fuels-ts/pull/2759#issuecomment-2225448996

**Comment by mvares** [comment]
> On the topic of fixing flakiness with timeouts:
> 
> * [fix: verification of `fuel-core` node killing #2759 (comment)](https://github.com/FuelLabs/fuels-ts/pull/2759#issuecomment-2225448996)

What's your advice? Should we wait for #2759 to be merged?

**Comment by petertonysmith94** [comment]
> > On the topic of fixing flakiness with timeouts:
> > 
> > * [fix: verification of `fuel-core` node killing #2759 (comment)](https://github.com/FuelLabs/fuels-ts/pull/2759#issuecomment-2225448996)
> 
> What's your advice? Should we wait for #2759 to be merged?

I would say that we're not fixing flakyness here - as the POA is `17s`, using the default Vitest timeout (`5s`) is no sufficient for the given test.

An increment to the timeout might be worthwhile after looking closer at the [CI failures](https://github.com/FuelLabs/fuels-ts/actions/runs/9957627412/job/27529493691?pr=2776#step:5:1533). 

Maybe a timeout of `22s` might be optimal, given that the POA is `17s` and default timeout is `5s`?

**Comment by mvares** [comment]
> An increment to the timeout might be worthwhile after looking closer at the [CI failures](https://github.com/FuelLabs/fuels-ts/actions/runs/9957627412/job/27529493691?pr=2776#step:5:1533).
> 
> Maybe a timeout of `22s` might be optimal, given that the POA is `17s` and default timeout is `5s`?

Well, I think that `22s` is reasonable. We can try it.

**Comment by arboleya** [comment]
I don't have the proper context and cannot dive into this right now to determine what should be done.

Besides flakiness/timeouts, another concern is when tests require so much time to run.

These intricacies here may be the reason why we're skipping the test.

**Comment by mvares** [comment]
Right. Should I close this PR?

**Comment by maschad** [comment]
> Right. Should I close this PR?

Yes, thanks for the effort.

**Pull request closed without merging**
