### PR TITLE
chore: adding demo apps

### PR DESCRIPTION
**Pull request by arboleya**
This PR adds app demos for:
 - NextJS
 - React - Using CRA
 - React - Using Vite

 > All apps are built on a `pretest` step _(see `package.json` scripts)_, to keep local `build` times faster.

These apps import `fuels` and log stuff to the console, but nothing else.

This validates that our build works locally with such tools via #1055.

I wonder if we want these apps in the repo since they're very bulky. For example, we could do these validations via parallel GitHub workflows. I just needed a quick and reliable way to validate things now, and this did the job, but I am happy to open new issues to do this after this goes through.

Curious to see what @FuelLabs/sdk-ts thinks.

### CODE REVIEW

**Review by Torres-ssf — DISMISSED** [review]

**Review by danielbate — DISMISSED** [review]
The bloat is worth it IMO, then we ensure they are kept in sync with the rest of the mono repo.

**Review by Dhaiwat10 — DISMISSED** [review]
I think this is a fair solution for now. I don't mind keeping these examples inside the monorepo if they don't slow any builds down

**Comment by nedsalk** [comment]
Could we ignore these apps in local development builds and just have them built in the pipeline? It seems to me that ignoring them locally would be okay because they aren't the focus of development. We'd then get the best of both worlds: unaffected build time and this PR serving its purpose via the pipeline build.

**Review by nedsalk — APPROVED** [review]
Could we ignore these apps in local development builds and just have them built in the pipeline? We'd then get the best of both worlds: unaffected local build time and this PR serving its purpose via the pipeline build validating that the SDK works with the tools.

**Comment by arboleya** [comment]
I left a note about build time on the PR description:

> All apps are built on a `pretest` step _(see `package.json` scripts)_, to keep local `build` times faster.

**Review by danielbate — APPROVED** [review]

**Review by Torres-ssf — APPROVED** [review]

**Pull request merged**
