### PR TITLE
fix: updating Quickstart and example dapp

### LINKED ISSUE #566: Update quickstart with new Wallet API
Update on the https://fuellabs.github.io/fuels-ts/QUICKSTART.html to use WalletUnlocked and WalletLocked on it.

### PR DESCRIPTION
**Pull request by jacobrosenthal**
- Close #566

Found some problems moving through `Quickstart.md`, Looks like a few `chainConfig.json` changes were missed in https://github.com/FuelLabs/fuels-ts/pull/563/files#diff-9e90a9d14248eb420074c47afb376fc8904d1dacef9f03408188b57cf0cd2388

The example also didnt run for me, so pasted my copy of the example on top as a commit as well. I seem to be using an older version of npm so package files are a mess, but otherwise probably fine.

Im obviously new here so I could be missing something, but this seems to work for me

### CODE REVIEW

**Comment by arboleya** [comment]
@jacobrosenthal Thank you!

@luizstacio I referenced a related issue that I believe this PR might close.

**Comment by jacobrosenthal** [comment]
Re the error, its dying on the test file. This wasnt checked in before. I could remove it

**Comment by arboleya** [comment]
@jacobrosenthal The test appears ok, but it fails because of this:
 - https://github.com/FuelLabs/fuels-ts/issues/584

**Review by luizstacio — APPROVED** [review]

**Comment by arboleya** [comment]
@jacobrosenthal The problem we had with the CI was fixed via the following:
 - #601 

You can try rolling back your tests to see if everything works as expected.

**Review by QuinnLee — APPROVED** [review]

**Comment by jacobrosenthal** [comment]
I dont think this needs anything from me? All the tests look green.

**Comment by jacobrosenthal** [comment]
This looks like its being deleted in https://github.com/FuelLabs/fuels-ts/pull/612 just close it?

**Comment by arboleya** [comment]
@camsjams Should we close this one in favor of #612?

**Pull request merged**
