### PR TITLE
docs: update string type docs to account for value length mismatch in `StringCoder`

### PR DESCRIPTION
**Pull request by danielbate**
#985 will have implications on the types documentation for strings in #950 , therefore this PR will update those docs and test cases.

### CODE REVIEW

**Comment by arboleya** [comment]
@danielbate It looks like tests are [failing](https://github.com/FuelLabs/fuels-ts/actions/runs/5013460886/jobs/8986565404?pr=1007#step:11:1396); see annotations [here](https://github.com/FuelLabs/fuels-ts/pull/1007/files#diff-fe82ae1e03e21899c0d39e45cb5c9c859f3f6dc9a044c6a4e8b0bd2ec6958f3eR41).

**Comment by danielbate** [comment]
> @danielbate It looks like tests are [failing](https://github.com/FuelLabs/fuels-ts/actions/runs/5013460886/jobs/8986565404?pr=1007#step:11:1396); see annotations [here](https://github.com/FuelLabs/fuels-ts/pull/1007/files#diff-fe82ae1e03e21899c0d39e45cb5c9c859f3f6dc9a044c6a4e8b0bd2ec6958f3eR41).

@arboleya Target/base branch (#950) just needed latest `master`, pipeline is passing now

**Review by arboleya — APPROVED** [review]

**Review by Torres-ssf — APPROVED** [review]
:rocket:

**Comment by Torres-ssf** [comment]
> This probably needs your sign off from you more so than others @Torres-ssf as #950 is in progress from yourself

Thanks for your work here @danielbate

**Pull request merged**
