### PR TITLE
ci: update pnpm to 9.7.1

### PR DESCRIPTION
**Pull request by maschad**
# Summary

I was tired of seeing the prompt to update pnpm 😄 

# Checklist

- [x] All **changes** are **covered** by **tests** (or not applicable)
- [x] All **changes** are **documented** (or not applicable)
- [x] I **reviewed** the **entire PR** myself (preferably, on GH UI)
- [x] I **described** all **Breaking Changes** (or there's none)

### CODE REVIEW

**Comment by maschad** [comment]
@petertonysmith94 I'm not quite sure how to update this on Vercel deployments, I'm not seeing any workflow files related to it nor am I seeing it on the [deployment settings](https://vercel.com/fuel-labs/fuels-ts/settings/general).

**Review by arboleya — APPROVED** [review]

**Review by nedsalk — APPROVED** [review]

**Review by danielbate — DISMISSED** [review]

**Comment by arboleya** [comment]
@maschad I went down this rabbit hole and clicked every link two levels deep, to no avail:
 - https://github.com/orgs/vercel/discussions/6865

Ultimately, it suggests turning off the `strictness` version in `.npmrc`, which doesn't seem like the best solution.

I did everything but this, and nothing worked.

**Review by Torres-ssf — APPROVED** [review]

**Review by Dhaiwat10 — APPROVED** [review]

**Comment by maschad** [comment]
> @maschad I went down this rabbit hole and clicked every link two levels deep, to no avail:
> 
> * [github.com/orgs/vercel/discussions/6865](https://github.com/orgs/vercel/discussions/6865)
> 
> Ultimately, it suggests turning off the `strictness` version in `.npmrc`, which doesn't seem like the best solution.
> 
> I did everything but this, and nothing worked.

Thanks for taking a look into this @arboleya, reading through that thread that you shared it seems that's the only available workaround at the moment, although I agree with you, it's not a real solution 😕

**Comment by arboleya** [comment]
@maschad Yes, annoying as it is, this is a low-priority thing. I'd say I prefer to keep using an outdated version rather than turn off strictness and risk us all running different versions, which could cause issues.

**Comment by maschad** [comment]
> @maschad Yes, annoying as it is, this is a low-priority thing. I'd say I prefer to keep using an outdated version rather than turn off strictness and risk us all running different versions, which could cause issues.

Agree here @arboleya , I'll move this PR to draft until a better resolution can be found.

**Comment by petertonysmith94** [comment]
@maschad do you think we could close this until we know what the resolution is?

**Comment by maschad** [comment]
Well I would say the resolution as it stands is that we can't upgrade until vercel resolves [this issue](https://github.com/vercel/vercel/issues/11607) so closing for now

**Pull request closed without merging**
