### PR TITLE
chore: configuring dependabot

### PR DESCRIPTION
**Pull request by arboleya**
Closes https://github.com/FuelLabs/fuels-ts/issues/2035

### CODE REVIEW

**Review by maschad — APPROVED** [review]

**Review by maschad — CHANGES_REQUESTED** [review]
We will probably need some configuration adjustments for the changesets

See https://github.com/FuelLabs/fuels-ts/pull/2063

**Comment by arboleya** [comment]
@maschad Should we merge it like this and address the changeset in another PR?

Meanwhile, could we manually add changesets to the `dependabot` PRs?

**Review by danielbate — APPROVED** [review]
Approving as I agree with [this comment](https://github.com/FuelLabs/fuels-ts/pull/2062#issuecomment-2061323384).

Depenbabot PR will fail validation without a changeset also? So we shouldn't miss it.

**Comment by maschad** [comment]
> Approving as I agree with [this comment](https://github.com/FuelLabs/fuels-ts/pull/2062#issuecomment-2061323384).
> 
> Depenbabot PR will fail validation without a changeset also? So we shouldn't miss it.

That's a good point, I was planning to address the issue here though to avoid the manual work in the future. But I will approve to unblock the work.

**Review by maschad — APPROVED** [review]

**Pull request merged**
