### PR TITLE
test: refactor `VecCoder` tests

### PR DESCRIPTION
**Pull request by danielbate**
Related to #753

This PR will:
- Introduce a seperate test file for the service under test
- Seperate test cases for `encode` and `decode`
- Remove snapshot tests to bring expectations into the same test file
- Remove redundant tests to more clearly report on code coverage

### CODE REVIEW

**Review by arboleya — APPROVED** [review]
This is pretty good stuff, although we need more test cases for covering more sub-types _(not only `number` or `boolean`)_ — I guess this might overlap with #933. (cc @camsjams)

```
----------------|---------|----------|---------|---------|---------------------------
File            | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------------|---------|----------|---------|---------|---------------------------
  vec.ts        |    87.5 |       50 |     100 |   86.95 | 31,40,57
```

**Comment by danielbate** [comment]
@arboleya more than happy to add more test cases. What would we expect this to look like? A single vector containing all possible sub-types? Or a separate test case for each sub type within a vector?

**Comment by arboleya** [comment]
@danielbate Good question; I suspect a single Vector might be cleaner.

However, I'm not sure about which types we currently support:
 - https://github.com/FuelLabs/fuels-ts/issues/933

Additional test cases could be added alongside the issue above.

**Comment by arboleya** [comment]
@camsjams What do you think about the above comments?

**Pull request merged**
